name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Download NSC_Builder
      run: |
        mkdir -p app/src/main/python/NSC_Builder
        curl -L https://github.com/julesontheroad/NSC_BUILDER/archive/refs/heads/master.zip -o nsc_builder.zip
        unzip -q nsc_builder.zip
        cp -r NSC_BUILDER-master/* app/src/main/python/NSC_Builder/

    - name: Fix sq_settings.py path
      run: |
        mv app/src/main/python/NSC_Builder/py/ztools/lib/sq_settings.py \
           app/src/main/python/NSC_Builder/py/ztools/

    - name: Debug: List contents of NSC_Builder after fix
      run: |
        echo "Verifying sq_settings.py location:"
        find app/src/main/python/NSC_Builder/py/ztools -name "sq_settings.py"

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: NSZ-Toolbox-APK
        path: app/build/outputs/apk/debug/app-debug.apk